### Importing important libraries.

In [136]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

### Importing OS and defining path for fetching data this folder.

In [137]:
import os
# .. by using this we can define the ouside way of folders for fetching data from any folder on the main folder if avilable.(relative path)
print("Files inside data folder:", os.listdir('../DataSets'))

Files inside data folder: ['purchase_behaviour.csv', 'transaction_data.xlsx']

### Data Fetching --

In [138]:
tran_df = pd.read_excel('../DataSets/transaction_data.xlsx')
transaction = pd.DataFrame(tran_df)
print(transaction.head())

    DATE  STORE_NBR  LYLTY_CARD_NBR  TXN_ID  PROD_NBR  \
0  43390          1            1000       1         5
1  43599          1            1307     348        66
2  43605          1            1343     383        61
3  43329          2            2373     974        69
4  43330          2            2426    1038       108

                                  PROD_NAME  PROD_QTY  TOT_SALES
0    Natural Chip        Compny SeaSalt175g         2        6.0
1                  CCs Nacho Cheese    175g         3        6.3
2    Smiths Crinkle Cut  Chips Chicken 170g         2        2.9
3    Smiths Chip Thinly  S/Cream&Onion 175g         5       15.0
4  Kettle Tortilla ChpsHny&Jlpno Chili 150g         3       13.8

In [139]:
behaviour_df = pd.read_csv('../DataSets/purchase_behaviour.csv')
transaction = pd.DataFrame(behaviour_df)
print(transaction.head())

   LYLTY_CARD_NBR               LIFESTAGE PREMIUM_CUSTOMER
0            1000   YOUNG SINGLES/COUPLES          Premium
1            1002   YOUNG SINGLES/COUPLES       Mainstream
2            1003          YOUNG FAMILIES           Budget
3            1004   OLDER SINGLES/COUPLES       Mainstream
4            1005  MIDAGE SINGLES/COUPLES       Mainstream

### Checking for null values --

In [140]:
tran_df.isnull().sum()

DATE              0
STORE_NBR         0
LYLTY_CARD_NBR    0
TXN_ID            0
PROD_NBR          0
PROD_NAME         0
PROD_QTY          0
TOT_SALES         0
dtype: int64

In [141]:
behaviour_df.isnull().sum()

LYLTY_CARD_NBR      0
LIFESTAGE           0
PREMIUM_CUSTOMER    0
dtype: int64

### Checking Outliers --

In [142]:
display(tran_df.describe())

,DATE,STORE_NBR,LYLTY_CARD_NBR,TXN_ID,PROD_NBR,PROD_QTY,TOT_SALES
count,264836.000000,264836.00000,2.648360e+05,2.648360e+05,264836.000000,264836.000000,264836.000000
mean,43464.036260,135.08011,1.355495e+05,1.351583e+05,56.583157,1.907309,7.304200
std,105.389282,76.78418,8.057998e+04,7.813303e+04,32.826638,0.643654,3.083226
min,43282.000000,1.00000,1.000000e+03,1.000000e+00,1.000000,1.000000,1.500000
25%,43373.000000,70.00000,7.002100e+04,6.760150e+04,28.000000,2.000000,5.400000
50%,43464.000000,130.00000,1.303575e+05,1.351375e+05,56.000000,2.000000,7.400000
75%,43555.000000,203.00000,2.030942e+05,2.027012e+05,85.000000,2.000000,9.200000
max,43646.000000,272.00000,2.373711e+06,2.415841e+06,114.000000,200.000000,650.000000

#### Indentifying customer having max purchase as outlier value of qty-

In [143]:
outlier_cust = tran_df[tran_df['PROD_QTY'] == 200]
outlier_cust

,DATE,STORE_NBR,LYLTY_CARD_NBR,TXN_ID,PROD_NBR,PROD_NAME,PROD_QTY,TOT_SALES
69762,43331,226,226000,226201,4,Dorito Corn Chp Supreme 380g,200,650.0
69763,43605,226,226000,226210,4,Dorito Corn Chp Supreme 380g,200,650.0

#### searching for outlier customer history to confirm that its a regular customer or not.

In [144]:
cust_history = tran_df[tran_df['LYLTY_CARD_NBR'] == 226000]
cust_history

,DATE,STORE_NBR,LYLTY_CARD_NBR,TXN_ID,PROD_NBR,PROD_NAME,PROD_QTY,TOT_SALES
69762,43331,226,226000,226201,4,Dorito Corn Chp Supreme 380g,200,650.0
69763,43605,226,226000,226210,4,Dorito Corn Chp Supreme 380g,200,650.0

#### Removing the outlier customer details.

In [145]:
tran_df = tran_df.drop(tran_df[tran_df['LYLTY_CARD_NBR'] == 226000].index) # above output will be empty because after identifying it we removed it.

In [146]:
behaviour_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 72637 entries, 0 to 72636
Data columns (total 3 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   LYLTY_CARD_NBR    72637 non-null  int64
 1   LIFESTAGE         72637 non-null  str
 2   PREMIUM_CUSTOMER  72637 non-null  str
dtypes: int64(1), str(2)
memory usage: 1.7 MB

### Identifying the outlier customer.

In [147]:
cst_history = behaviour_df[behaviour_df['LYLTY_CARD_NBR'] == 226000]
cst_history

       LYLTY_CARD_NBR       LIFESTAGE PREMIUM_CUSTOMER
59694          226000  OLDER FAMILIES          Premium

#### Removing that outlier customer from behaviour table.

In [148]:
behaviour_df = behaviour_df.drop(behaviour_df[behaviour_df['LYLTY_CARD_NBR'] == 226000].index) # above output will be empty because after identifying it we removed it.

### Fixing date format in transaction table.

In [149]:
import dateutil.parser as parser

In [150]:
##def clean_date(date):
##    try:
##      return parser.parse(str(date))
##    except:
##       return pd.NaT 
## This will not work in this case because of the date format is in number of days since 1899-12-30. So we will use another method to convert it.

In [151]:
tran_df.head()

,DATE,STORE_NBR,LYLTY_CARD_NBR,TXN_ID,PROD_NBR,PROD_NAME,PROD_QTY,TOT_SALES
0,43390,1,1000,1,5,Natural Chip Compny SeaSalt175g,2,6.0
1,43599,1,1307,348,66,CCs Nacho Cheese 175g,3,6.3
2,43605,1,1343,383,61,Smiths Crinkle Cut Chips Chicken 170g,2,2.9
3,43329,2,2373,974,69,Smiths Chip Thinly S/Cream&Onion 175g,5,15.0
4,43330,2,2426,1038,108,Kettle Tortilla ChpsHny&Jlpno Chili 150g,3,13.8

In [152]:
tran_df['DATE'] = pd.to_datetime(tran_df['DATE'],unit='D', origin='1899-12-30',errors='coerce') # text coverted into date time format by using this method.
tran_df.head()

,DATE,STORE_NBR,LYLTY_CARD_NBR,TXN_ID,PROD_NBR,PROD_NAME,PROD_QTY,TOT_SALES
0,2018-10-17,1,1000,1,5,Natural Chip Compny SeaSalt175g,2,6.0
1,2019-05-14,1,1307,348,66,CCs Nacho Cheese 175g,3,6.3
2,2019-05-20,1,1343,383,61,Smiths Crinkle Cut Chips Chicken 170g,2,2.9
3,2018-08-17,2,2373,974,69,Smiths Chip Thinly S/Cream&Onion 175g,5,15.0
4,2018-08-18,2,2426,1038,108,Kettle Tortilla ChpsHny&Jlpno Chili 150g,3,13.8

### Feature extraction -- In this we will extract packet size from its description(product_name).

In [153]:
tran_df['PACK_SIZE'] = tran_df['PROD_NAME'].str.extract(r'(\d+)')

In [154]:
tran_df.head(10)

,DATE,STORE_NBR,LYLTY_CARD_NBR,TXN_ID,PROD_NBR,PROD_NAME,PROD_QTY,TOT_SALES,PACK_SIZE
0,2018-10-17,1,1000,1,5,Natural Chip Compny SeaSalt175g,2,6.0,175
1,2019-05-14,1,1307,348,66,CCs Nacho Cheese 175g,3,6.3,175
2,2019-05-20,1,1343,383,61,Smiths Crinkle Cut Chips Chicken 170g,2,2.9,170
3,2018-08-17,2,2373,974,69,Smiths Chip Thinly S/Cream&Onion 175g,5,15.0,175
4,2018-08-18,2,2426,1038,108,Kettle Tortilla ChpsHny&Jlpno Chili 150g,3,13.8,150
5,2019-05-19,4,4074,2982,57,Old El Paso Salsa Dip Tomato Mild 300g,1,5.1,300
6,2019-05-16,4,4149,3333,16,Smiths Crinkle Chips Salt & Vinegar 330g,1,5.7,330
7,2019-05-16,4,4196,3539,24,Grain Waves Sweet Chilli 210g,1,3.6,210
8,2018-08-20,5,5026,4525,42,Doritos Corn Chip Mexican Jalapeno 150g,1,3.9,150
9,2018-08-18,7,7150,6900,52,Grain Waves Sour Cream&Chives 210G,2,7.2,210

### Extracting brand name.

In [158]:
tran_df['BRAND_NAME'] = tran_df['PROD_NAME'].str.extract(r'^([a-zA-Z]+)')

In [162]:
tran_df.head(10)

,DATE,STORE_NBR,LYLTY_CARD_NBR,TXN_ID,PROD_NBR,PROD_NAME,PROD_QTY,TOT_SALES,PACK_SIZE,BRAND_NAME
0,2018-10-17,1,1000,1,5,Natural Chip Compny SeaSalt175g,2,6.0,175,Natural
1,2019-05-14,1,1307,348,66,CCs Nacho Cheese 175g,3,6.3,175,CCs
2,2019-05-20,1,1343,383,61,Smiths Crinkle Cut Chips Chicken 170g,2,2.9,170,Smiths
3,2018-08-17,2,2373,974,69,Smiths Chip Thinly S/Cream&Onion 175g,5,15.0,175,Smiths
4,2018-08-18,2,2426,1038,108,Kettle Tortilla ChpsHny&Jlpno Chili 150g,3,13.8,150,Kettle
5,2019-05-19,4,4074,2982,57,Old El Paso Salsa Dip Tomato Mild 300g,1,5.1,300,Old
6,2019-05-16,4,4149,3333,16,Smiths Crinkle Chips Salt & Vinegar 330g,1,5.7,330,Smiths
7,2019-05-16,4,4196,3539,24,Grain Waves Sweet Chilli 210g,1,3.6,210,Grain
8,2018-08-20,5,5026,4525,42,Doritos Corn Chip Mexican Jalapeno 150g,1,3.9,150,Doritos
9,2018-08-18,7,7150,6900,52,Grain Waves Sour Cream&Chives 210G,2,7.2,210,Grain

### Cheking for brand name.

In [170]:
bran = tran_df[tran_df['BRAND_NAME'] == 'RRD']
bran

,DATE,STORE_NBR,LYLTY_CARD_NBR,TXN_ID,PROD_NBR,PROD_NAME,PROD_QTY,TOT_SALES,PACK_SIZE,BRAND_NAME
92,2019-05-18,120,120226,123743,67,RRD Chilli& Coconut 150g,1,2.7,150,RRD
118,2019-05-19,164,164183,164919,67,RRD Chilli& Coconut 150g,1,2.7,150,RRD
140,2018-08-16,191,191200,192940,53,RRD Sweet Chilli & Sour Cream 165g,1,3.0,165,RRD
294,2019-01-17,5,5018,4467,53,RRD Sweet Chilli & Sour Cream 165g,2,6.0,165,RRD
302,2018-08-11,5,5028,4535,67,RRD Chilli& Coconut 150g,2,5.4,150,RRD
...,...,...,...,...,...,...,...,...,...,...
264752,2018-07-30,268,268365,264802,103,RRD Steak & Chimuchurri 150g,1,2.7,150,RRD
264761,2019-06-21,269,269125,265778,11,RRD Pc Sea Salt 165g,2,6.0,165,RRD
264778,2019-06-02,269,269204,266273,67,RRD Chilli& Coconut 150g,2,5.4,150,RRD
264781,2019-02-08,269,269222,266383,11,RRD Pc Sea Salt 165g,2,6.0,165,RRD
264814,2018-08-30,271,271193,269364,10,RRD SR Slow Rst Pork Belly 150g,2,5.4,150,RRD

### Check for unique brand name so that same names can be replace with one sigle name so that no miss calculation will happen.

In [163]:
print(tran_df['BRAND_NAME'].unique()) # checking for unique name for identifying the names of brand.

<StringArray>
[   'Natural',        'CCs',     'Smiths',     'Kettle',        'Old',
      'Grain',    'Doritos',   'Twisties',         'WW',      'Thins',
     'Burger',        'NCC',   'Cheezels',     'Infzns',        'Red',
   'Pringles',     'Dorito',  'Infuzions',      'Smith',    'GrnWves',
   'Tyrrells',       'Cobs', 'Woolworths',     'French',        'RRD',
   'Tostitos',    'Cheetos',      'Snbts',   'Sunbites']
Length: 29, dtype: str